Online_Shop/Controllers/CheckoutController.cs
using Online_Shop.Models;
using Online_Shop.Models.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PagedList;

namespace Online_Shop.Controllers
{
    [SessionAuthentication]
    public class CheckoutController : BaseController
    {
        
        public ActionResult Index(int? page)
        {
            var orders = db.Users.Find(((User)Session["User"]).Id).Orders.OrderByDescending(o => o.Status).ToList();
            var list = (List<Order>)TempData["Orders"];
            if (list != null)
            {
                TempData["Orders"] = list;
                return View(list.ToPagedList(page ?? 1, 10));
            }

            TempData["Orders"] = orders;
            return View(orders.ToPagedList(page ?? 1, 10));

        }
        [HttpPost]
        public ActionResult Index (int? page, string searchString)
        {
            var orders = db.Users.Find(((User)Session["User"]).Id).Orders.OrderByDescending(o => o.Status).ToList();
            var list = new List<Order>();
            if (!String.IsNullOrEmpty(searchString))
            {
                list = orders.Where(o => o.Customer_name.Contains(searchString) ||
                o.Created_date.ToString().Contains(searchString) ||
                o.Phone_number.Contains(searchString) ||
                o.Place_of_receipt.Contains(searchString) ||
                o.Note.Contains(searchString)).OrderByDescending(o => o.Status).ToList();
            }
            else
            {
                list = orders.OrderByDescending(o => o.Status).ToList();
            }
            TempData["Orders"] = list;
            return View(list.ToPagedList(page ?? 1, 10));
        }
      

        // GET: Checkout
        public ActionResult Create()
        {
           if (Session[Convert.ToString(((User)Session["User"]).Id)] == null)
                return RedirectToAction("Index", "Cart");
            if (((List<ProductCart>)Session[Convert.ToString(((User)Session["User"]).Id)]).Count == 0)
                return RedirectToAction("Index", "Cart");
            else
            {
                List<ProductCart> list = (List<ProductCart>)Session[Convert.ToString(((User)Session["User"]).Id)];
                foreach (ProductCart item in list)
                {
                    Product product = db.Products.FirstOrDefault(p => p.Id == item.Id);
                    if (item.Quantity > product.Quantity)
                    {
                        Session["Message"] = "The order quantity of" + product.Name + " exceeds its quantity in stock";
                        return RedirectToAction("Index", "Cart");
                    } 
                }
            }

            User user = (User)Session["User"];
            List<ProductCart> cart = (List<ProductCart>)Session[Convert.ToString(((User)Session["User"]).Id)];
            List<ProductCartItem> items = new List<ProductCartItem>();
            decimal total = 0;
            if (cart != null)
            {
                foreach (ProductCart i in cart)
                {
                    Product product = db.Products.Find(i.Id);
                    items.Add(new ProductCartItem()
                    {
                        Product = product,
                        Quantity = i.Quantity

                    });
                    total += product.Price * i.Quantity;
                }

            }
            Session["Total"] = total;
            if (((User)Session["User"]).Address.ToLower().Contains("ha noi") || ((User)Session["User"]).Address.ToLower().Contains("hà nội"))
                ViewBag.Ship_Price = (decimal) 10;
            else
                ViewBag.Ship_Price = (decimal)20;
            Order order = new Order()
            {
                Customer_name = user.Name,
                Phone_number = user.Phone_number,
                Place_of_receipt = user.Address,
                User_id = ((User)Session["User"]).Id

            };
            List<Promotion> promotions = db.Promotions.Where(p => DateTime.Compare(DateTime.Now, p.End_date) < 0 && p.Quantity_left > 0 && DateTime.Compare(p.Begin_date, DateTime.Now) <= 0).ToList();
            var promotionDescs = new List<PromotionDesc>();
            foreach (var item in promotions)
            {
                promotionDescs.Add(new PromotionDesc { Id = item.Id, Desc = "(Discount: " + item.Percent_discount + "%): " + item.Short_desc });
            }
            return View(new OrderPromotions() { Order = order, Promotions = promotionDescs });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OrderPromotions op)
        {
            if (ModelState.IsValid)
            {
                
                List<ProductCart> list = (List<ProductCart>)Session[Convert.ToString(((User)Session["User"]).Id)];
                if (((User)Session["User"]).Address.ToLower().Contains("ha noi") || ((User)Session["User"]).Address.ToLower().Contains("hà nội"))
                    op.Order.Ship_price = (decimal)10;
                else
                        op.Order.Ship_price = (decimal)20;
                decimal total_price = 0;
                foreach (ProductCart item in list)
                {
                    Product product = db.Products.FirstOrDefault(p => p.Id == item.Id);
                    if (item.Quantity >product.Quantity)
                    {
                        Session["Message"] = "The order quantity of"+product.Name+" exceeds its quantity in stock";
                        return RedirectToAction("Index", "Cart");
                    }
                    total_price += product.Price * item.Quantity;
                }
                foreach (ProductCart item in list)
                {
                    Product product = db.Products.FirstOrDefault(p => p.Id == item.Id);
                    product.Quantity -= item.Quantity;
                }
                if(op.Order.Note ==null)
                    op.Order.Note = "";
                op.Order.Created_date = DateTime.Now;
                op.Order.Status = "Pending";
                op.Order.Total_Price = (decimal)(total_price*(100 - db.Promotions.FirstOrDefault(o => o.Id==op.Order.Promotion_id).Percent_discount) / 100) 
                                        + op.Order.Ship_price;
                db.Orders.Add(op.Order);
                db.Promotions.FirstOrDefault(o => o.Id == op.Order.Promotion_id).Quantity_left = db.Promotions.FirstOrDefault(o => o.Id == op.Order.Promotion_id).Quantity_left - 1;
                db.SaveChanges();
                var order_id = op.Order.Id;
                
                foreach (ProductCart item in list)
                {
                    var product = db.Products.FirstOrDefault(p => p.Id == item.Id);
                    db.Order_Product.Add(new Order_Product()
                    {
                        Order_id = order_id,
                        Product_id = product.Id,
                        Quantity = item.Quantity,
                        Price = product.Price * item.Quantity,
                        Created_at = DateTime.Now,
                        User_id = ((User)Session["User"]).Id
                    });

                }
                db.SaveChanges();
                Session[Convert.ToString(((User)Session["User"]).Id)] = new List<ProductCart>();
                Session["Message"] = "Your order created successfully. QTD shop's staff will contact you after 5 minutes.";
                return RedirectToAction("Index", "Home");
            }
            
            var promotions = db.Promotions.Where(p => DateTime.Compare(DateTime.Now, p.End_date) < 0).ToList();
            var promotionDescs = new List<PromotionDesc>();
            foreach (var item in promotions)
            {
                promotionDescs.Add(new PromotionDesc { Id = item.Id, Desc = "(Discount: " + item.Percent_discount + "%): " + item.Short_desc });
            }
            op.Promotions = promotionDescs;
            return View(op);
        }

        public ActionResult Detail(int? id )
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Order order = db.Orders.Find(id);
            List<Order_Product> products = db.Order_Product.Where(op => op.Order_id == id).ToList();
            OrderProductsPromotions orderProductsPromotions = new OrderProductsPromotions()
            {
                Order = order,
                Order_Products = products,
                Promotions = null
            };
            return View(orderProductsPromotions);
        }
       
    }
}

Online_Shop/Views/Checkout/Create.cshtml
@model Online_Shop.Models.DTO.OrderPromotions
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="breadcrumbs">
    <div class="container">
        <ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
            <li><a href="/Home"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
            <li class="active">Checkout</li>
        </ol>
    </div>
</div>
<div class="checkout">
    <div class="container">
        <div class="checkout-right animated wow slideInUp" data-wow-delay=".5s">



            @using (Html.BeginForm("Create", "Checkout", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    <h3>Order</h3>
                    <hr />
                    @Html.HiddenFor(model => model.Order.User_id)
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Order.Customer_name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Order.Customer_name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Order.Customer_name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Order.Phone_number, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Order.Phone_number, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Order.Phone_number, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Order.Place_of_receipt, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Order.Place_of_receipt, new { htmlAttributes = new { @class = "form-control" , onchange="ShipPriceCount(this.value)"} })
                            @Html.ValidationMessageFor(model => model.Order.Place_of_receipt, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Order.Note, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Order.Note, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Order.Note, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Order.Payment_method, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Order.Payment_method, new List<SelectListItem>() {
                                new SelectListItem { Selected = false, Text = "Cash On Delivery", Value = "Cash On Delivery"},
                                new SelectListItem { Selected = false, Text = "Transfer money", Value = "Transfer money (Card ID: 123456789)" },

                            }, new { @class = "form-control"})
                            @Html.ValidationMessageFor(model => model.Order.Payment_method, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">

                        @Html.LabelFor(model => model.Order.Promotion_id, "Promotion_id", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Order.Promotion_id, new SelectList(Model.Promotions, "Id", "Desc"), htmlAttributes: new { @class = "form-control" , onclick="Discount(this)"})
                            @Html.ValidationMessageFor(model => model.Order.Promotion_id, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    @*<div class="form-group">
                            @Html.LabelFor(model => model.Order.Total_Price, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DisplayFor(model => model.Order.Total_Price, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>*@
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-12">
                            <input type="submit" value="Make Order" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            }
                <div class="checkout-left">
                    <div class="checkout-left-basket animated wow slideInLeft" data-wow-delay=".5s">
                        <h4>About Bill</h4>
                        <ul>
                            <li>Sub Total:  <span id="SubTotal">$@Session["Total"] </span></li>
                            <li >Ship Price:  <span id="Ship_price">$@ViewBag.Ship_Price</span></li>
                            <li>Discount: <i></i> <span id="Discount">$0 </span></li>
                            <li> <i></i> <span></span></li>
                            <li>Total <i>-</i> <span id="Total">$@((decimal)Session["Total"] + ViewBag.Ship_Price)</span></li>
                        </ul>
                    </div>
                    <div class="checkout-right-basket animated wow slideInRight" data-wow-delay=".5s">
                        <a href="/Cart"><span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>Back To Cart</a>
                    </div>
                    <div class="clearfix"> </div>
                </div>
            @*<div>
                    @Html.ActionLink("Back to Cart", "Index", "Cart")
                </div>*@
        </div>

    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script>
    var promotionList = JSON.parse('@Html.Raw(Json.Encode(Model.Promotions))');

    function Discount(e) {
        var clientId = $(e).find('option:selected').val();
        console.log(clientId);
        var desc = "";
        for (i = 0; i < promotionList.length; i++) {
            if (promotionList[i].Id == clientId) {
                console.log(typeof (promotionList[i].Desc));
                desc = promotionList[i].Desc;
                desc = desc.split(')')[0].split(' ')[1];
                desc = desc.substr(0, desc.length - 1);
                console.log(desc);
                $('#Discount').text(desc + "%");
                $('#Total').text('$' + Math.round(Number($('#SubTotal').text().substr(1)) * (100 - Number(desc)) / 100 + Number($('#Ship_price').text().substr(1)
                )));
            }
               
        }
    }
    function ShipPriceCount(val) {
        console.log(val.toLowerCase());
        var ship_price = 20
        if (val.toString().toLowerCase().includes("ha noi") || val.toString().toLowerCase().includes("hà nội")) {
            console.log(val + "  true");
            ship_price = 10;
        }
        $('#Ship_price').text("$" + ship_price);
        $('#Total').text('$' + Math.round(Number($('#SubTotal').text().substr(1)) * (100 - Number($('#Discount').text().substr(0, $('#Discount').text().length -1 ))) / 100 + ship_price));
    }
    </script>
}

Online_Shop/Views/Checkout/Index.cshtml
@model  PagedList.IPagedList<Online_Shop.Models.Order>
@using PagedList.Mvc
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <link rel="stylesheet" href="~/Scripts/PaginationStyle.css" />
</head>


<div class="breadcrumbs">
    <div class="container">
        <ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
            <li><a href="index.html"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
            <li class="active">My Orders</li>
        </ol>
    </div>
</div>
<div class="checkout">
    <div class="container">
        <div class="checkout-right animated wow slideInUp" data-wow-delay=".5s">
            <div class=" card-body">
                <div class=" col-lg-12 grid-margin stretch-card">
                    @using (Html.BeginForm("Index", "Checkout", FormMethod.Post))
                    {
                        <div class="input-group rounded">

                            <p>
                                @Html.TextBox("searchString", null, new { @class = "form-control rounded", @placeholder = "Search Order" })
                            </p>

                        </div>
                    }
                </div>
                @if (Model.Count() != 0)
                {
                    <table class=" table table-hover">
                        <tr>

                            <th>Customer</th>
                            <th>Phone Number</th>
                            <th>Place of Receipt</th>
                            <th>Payment Method</th>
                            <th>Total Price</th>
                            <th>Promotion</th>
                            <th>Created Date</th>
                            <th>Status</th>
                            <th> Actions</th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr class="rem-@item.Id">


                                <td>
                                    @Html.DisplayFor(modelItem => item.Customer_name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Phone_number)
                                </td>
                                <td width="300px">
                                    @Html.DisplayFor(modelItem => item.Place_of_receipt)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Payment_method)
                                </td>
                                <td>
                                    $@Html.DisplayFor(modelItem => item.Total_Price)
                                </td>
                                <td>
                                    @if (item.Promotion == null)
                                    {
                                        <em><b>None</b></em>
                                    }
                                    else
                                    {
                                        @Html.DisplayFor(modelItem => item.Promotion.Name)
                                    }
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Created_date)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Status)
                                </td>
                                <td>
                                    @using (Html.BeginForm("Detail", "CheckOut", new { id = item.Id }, FormMethod.Get, new { @Style = "display : inline" }))
                                    {
                                        <button type="submit" class="btn btn-primary ">
                                            Detail
                                        </button>
                                    }
                                </td>
                            </tr>
                        }

                    </table>}
                else
                {
                    <em><b>No Result</b></em>
                }
            </div>
        </div>
    </div>
</div>

<div class="pagination">

    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }), new PagedListRenderOptions
                {
                         MaximumPageNumbersToDisplay = 5

                     })

</div>


@section Scripts{


    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryunobtrusive")
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
}